export const SCORING_CONSTANTS = Object.freeze({
  scoringVersion: 2,
  baseScore: [0, 0, 0, 0, 0],
  scoreValue: [
    [11, 0.6, 9],
    [11, 0.6, 9],
    [11, 0.6, 9],
    [3, 0.6, 9],
    [0, 0.6, 0],
  ],
  friendshipGreenDiscount: 10,
  statValueMultiplier: [1, 1, 1, 1, 1, 0.5],
  spiritExplosion: [16, 16, 16, 6, 11],
  specialTraining: [15, 12, 9, 7, 0],
  witSpecialMultiplier: [1.0, 1.0],
  npcWeight: [5, 5, 5, 3, 0],
  palFriendshipScore: [8.0, 5.7, 1.8],
  palCardMultiplier: 10,
  summerScoreThreshold: 34,
  witRaceSearchThreshold: 15,
  statCapPenalties: [[95, 0], [90, 70], [80, 80], [70, 90]],
});

export function createScoringDefaults() {
  return {
    scoringVersion: SCORING_CONSTANTS.scoringVersion,
    baseScore: [...SCORING_CONSTANTS.baseScore],
    scoreValueJunior: [...SCORING_CONSTANTS.scoreValue[0]],
    scoreValueClassic: [...SCORING_CONSTANTS.scoreValue[1]],
    scoreValueSenior: [...SCORING_CONSTANTS.scoreValue[2]],
    scoreValueSeniorAfterSummer: [...SCORING_CONSTANTS.scoreValue[3]],
    scoreValueFinale: [...SCORING_CONSTANTS.scoreValue[4]],
    friendshipGreenDiscount: SCORING_CONSTANTS.friendshipGreenDiscount,
    statValueMultiplier: [...SCORING_CONSTANTS.statValueMultiplier],
    spiritExplosionJunior: [...SCORING_CONSTANTS.spiritExplosion],
    spiritExplosionClassic: [...SCORING_CONSTANTS.spiritExplosion],
    spiritExplosionSenior: [...SCORING_CONSTANTS.spiritExplosion],
    spiritExplosionSeniorAfterSummer: [...SCORING_CONSTANTS.spiritExplosion],
    spiritExplosionFinale: [...SCORING_CONSTANTS.spiritExplosion],
    specialJunior: SCORING_CONSTANTS.specialTraining[0],
    specialClassic: SCORING_CONSTANTS.specialTraining[1],
    specialSenior: SCORING_CONSTANTS.specialTraining[2],
    specialSeniorAfterSummer: SCORING_CONSTANTS.specialTraining[3],
    specialFinale: SCORING_CONSTANTS.specialTraining[4],
    witSpecialJunior: SCORING_CONSTANTS.witSpecialMultiplier[0],
    witSpecialClassic: SCORING_CONSTANTS.witSpecialMultiplier[1],
    npcWeight: [...SCORING_CONSTANTS.npcWeight],
    palFriendshipScore: [...SCORING_CONSTANTS.palFriendshipScore],
    palCardMultiplier: SCORING_CONSTANTS.palCardMultiplier,
    summerScoreThreshold: SCORING_CONSTANTS.summerScoreThreshold,
    witRaceSearchThreshold: SCORING_CONSTANTS.witRaceSearchThreshold,
    statCapPenalties: SCORING_CONSTANTS.statCapPenalties.map((p) => [...p]),
  };
}
